package com.xxmrk888ytxx.portal.domain.model

import kotlinx.serialization.Serializable

/**
 * Incoming unlock request currently pending on the watch.
 *
 * [decisionId] is generated by the phone and lets all phone/watch UIs converge on the first
 * unlock/cancel decision. Completed requests can still be displayed when a stale notification is
 * opened after the phone has already finalized the request.
 */
@Serializable
data class IncomingUnlockRequest(
    val decisionId: String,
    val clientId: String,
    val deviceName: String,
    val isCompleted: Boolean = false
)
